"""
ShipPulse - Workflow & Workspace Microservice (Port 5002)
Handles virtual repository files, AST-based YAML linting, workflow generation, and command execution.
"""

import sys
import os
import time
import secrets
import logging
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

# Add backend directory to sys.path to access common package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from common.config import settings
from common.schemas import (
    HealthResponse,
    RepoFilesResponse,
    RepoFileRecord,
    SingleFileResponse,
    SaveFileRequest,
    SaveFileResponse,
    GenerateWorkflowRequest,
    GenerateWorkflowResponse,
    ExecCommandRequest,
    ExecCommandResponse,
    YamlLintRequest,
    YamlLintResponse,
    YamlLintError
)

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [%(levelname)s] [WorkflowService] %(message)s")
logger = logging.getLogger("workflow_service")

app = FastAPI(
    title="ShipPulse - Workflow & Workspace Service",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.CORS_ORIGIN] if settings.CORS_ORIGIN != "*" else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

virtual_repo_files: Dict[str, Dict[str, str]] = {
    "scientific--calculator-2": {
        "package.json": '{\n  "name": "scientific--calculator-2",\n  "version": "2.4.0",\n  "scripts": {\n    "test": "node tests/calculator.test.js",\n    "build": "echo \'Build complete\'"\n  }\n}\n',
        "src/calculator.js": '// ShipPulse Managed File\nfunction add(a, b) { return a + b; }\nfunction multiply(a, b) { return a * b; }\nmodule.exports = { add, multiply };\n',
        "tests/calculator.test.js": 'const { add, multiply } = require("../src/calculator");\nconsole.log("PASS: 2+2=4");\n'
    }
}


@app.get("/health", response_model=HealthResponse)
async def health_check():
    return HealthResponse(
        status="healthy",
        service="Workflow & Workspace Service",
        timestamp=int(time.time()),
        version="1.0.0"
    )


@app.get("/repos/{owner}/{repo}/files", response_model=RepoFilesResponse)
async def list_repo_files(owner: str, repo: str):
    """Lists repository files for inspection and hot-patch editing."""
    clean_repo = repo.replace(".git", "")
    files_map = virtual_repo_files.get(clean_repo) or virtual_repo_files.get("scientific--calculator-2", {})

    file_list: List[RepoFileRecord] = []
    for f_path, content in files_map.items():
        parts = f_path.split("/")
        file_list.append(RepoFileRecord(
            path=f_path,
            name=parts[-1],
            type="file",
            size=len(content)
        ))

    return RepoFilesResponse(
        repository=f"{owner}/{clean_repo}",
        branch="main",
        files=file_list
    )


@app.get("/repos/{owner}/{repo}/file", response_model=SingleFileResponse)
async def get_repo_file(owner: str, repo: str, path: str = Query(default="package.json")):
    """Retrieves file content."""
    clean_repo = repo.replace(".git", "")
    files_map = virtual_repo_files.get(clean_repo) or virtual_repo_files.get("scientific--calculator-2", {})
    content = files_map.get(path, "// File not found")

    return SingleFileResponse(
        repository=clean_repo,
        path=path,
        content=content
    )


@app.post("/repos/{owner}/{repo}/save-file", response_model=SaveFileResponse)
async def save_repo_file(owner: str, repo: str, payload: SaveFileRequest):
    """Hot-patches or saves a file in the workspace container."""
    clean_repo = repo.replace(".git", "")
    if not payload.path:
        raise HTTPException(status_code=400, detail="File path is required")

    if clean_repo not in virtual_repo_files:
        virtual_repo_files[clean_repo] = {}
    virtual_repo_files[clean_repo][payload.path] = payload.content

    return SaveFileResponse(
        success=True,
        message=f"File '{payload.path}' updated successfully in {clean_repo}",
        repository=clean_repo,
        path=payload.path,
        size=len(payload.content),
        timestamp=datetime.now(timezone.utc).isoformat()
    )


@app.post("/repos/{owner}/{repo}/generate-workflow", response_model=GenerateWorkflowResponse)
async def generate_workflow(owner: str, repo: str, payload: GenerateWorkflowRequest):
    """Generates and commits a standardized GitHub Actions CI/CD workflow YAML."""
    clean_repo = repo.replace(".git", "")
    yaml_content = payload.yamlContent

    if not yaml_content:
        yaml_content = f"""# Auto-generated by ShipPulse
name: ShipPulse CI/CD

on:
  push:
    branches: [ "{payload.branch}" ]
  pull_request:
    branches: [ "{payload.branch}" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run automated test suite
        run: npm test --if-present

      - name: Build production bundle
        run: npm run build --if-present
"""

    if clean_repo not in virtual_repo_files:
        virtual_repo_files[clean_repo] = {}
    virtual_repo_files[clean_repo][payload.filePath] = yaml_content

    return GenerateWorkflowResponse(
        success=True,
        message=f"Workflow '{payload.filePath}' created & committed to {owner}/{clean_repo} [branch: {payload.branch}]",
        repository=f"{owner}/{clean_repo}",
        filePath=payload.filePath,
        branch=payload.branch,
        commit={
            "sha": secrets.token_hex(4),
            "message": payload.commitMessage,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    )


@app.post("/repos/{owner}/{repo}/exec", response_model=ExecCommandResponse)
async def execute_debug_command(owner: str, repo: str, payload: ExecCommandRequest):
    """Simulates command diagnostics and test runner execution with strict injection guardrails."""
    command = payload.command.strip()
    clean_repo = repo.replace(".git", "")
    iso_time = datetime.now(timezone.utc).isoformat()

    # Security Guardrail: Reject shell injection payloads & disallowed executables
    disallowed_tokens = [";", "&&", "||", "`", "$(", ">", "<", "rm ", "curl ", "wget ", "sudo ", "chmod ", "eval ", "bash -i"]
    if any(token in command.lower() for token in disallowed_tokens):
        logger.warning(f"[Security] Blocked potentially malicious command: {command}")
        raise HTTPException(
            status_code=400,
            detail="Command execution policy violation: Potentially unsafe command or shell injection sequence detected."
        )

    allowed_prefixes = ("npm", "npx", "ng", "node", "echo", "git", "pytest", "python")
    if not command.startswith(allowed_prefixes):
        logger.warning(f"[Security] Command outside permitted whitelist: {command}")
        raise HTTPException(
            status_code=400,
            detail=f"Command execution policy violation: Command must start with one of {allowed_prefixes}"
        )

    if command == "npm test":
        output = f"""> {clean_repo}@1.0.0 test
> vitest run

  ✓ test/app.spec.ts (1 test passed) [42ms]
  Test Files  1 passed (1)
  Tests       1 passed (1)
  Duration    0.85s
"""
        exit_code = 0
    elif command in ["npm run build", "ng build"]:
        output = f"""> {clean_repo}@1.0.0 build
> ng build --configuration production
Application bundle generation complete. [0 errors, 0 warnings]
"""
        exit_code = 0
    elif "echo" in command:
        output = command.replace("echo", "").strip()
        exit_code = 0
    else:
        output = f"$ {command}\nCommand completed successfully with returncode 0."
        exit_code = 0

    return ExecCommandResponse(
        command=command,
        output=output,
        exitCode=exit_code,
        durationMs=48,
        timestamp=iso_time
    )


@app.post("/yaml/lint", response_model=YamlLintResponse)
async def lint_yaml(payload: YamlLintRequest):
    """Validates and parses YAML content using PyYAML."""
    content = payload.content or ""
    try:
        parsed = yaml.safe_load(content)
        return YamlLintResponse(
            isValid=True,
            errors=[],
            warnings=[],
            parsed=parsed if isinstance(parsed, dict) else {}
        )
    except yaml.YAMLError as exc:
        line = 1
        col = 1
        if hasattr(exc, "problem_mark") and exc.problem_mark:
            line = exc.problem_mark.line + 1
            col = exc.problem_mark.column + 1
        return YamlLintResponse(
            isValid=False,
            errors=[YamlLintError(
                message=str(exc),
                line=line,
                column=col,
                code="SYNTAX_ERROR"
            )],
            warnings=[]
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=settings.WORKFLOW_PORT)
